package main

import (
	"bytes"
	"fmt"
	"os"
	"reflect"
	"strings"
)

//go:generate go run . gen-ts

// GenTSCmd emits the TypeScript side of the writer↔reader data contract
// (frontend/src/js/format.gen.ts): the idx format constants and the wire
// shapes of the JSON the backend writes (db.gz, JSONL data packs),
// reflected from the live Go declarations so every format atom has
// exactly one source. Hidden dev tooling: run via `make generate`
// (`go generate ./...`); `make verify` runs `--check` so a stale file
// fails loudly.
type GenTSCmd struct {
	Out   string `default:"../frontend/src/js/format.gen.ts" help:"Output path (default is relative to backend/)."`
	Check bool   `help:"Verify the output file matches what would be generated; non-zero exit on drift."`
}

// tsConsts maps the Go format constants to their exported TS names. The
// values are referenced, not copied — changing a Go const regenerates a
// changed TS file.
var tsConsts = []struct {
	name  string
	value int
	doc   string
}{
	{"IDX_PACK_SIZE", idxPackSize, "entries per finalized idx pack (split threshold)"},
	{"IDX_STATE_SIZE", idxStateSize, "bytes: the 3 leading uint32 LE idx-header state fields (fetchedAt/packId/packOff bases)"},
	{"CHAN_ID_SLOTS", idxChanSlots, "channel-id ceiling: chan_id is one byte, the idx header reserves this many chanCount slots"},
	{"IDX_HEADER_SIZE", idxHeaderSize, "bytes: IDX_STATE_SIZE + CHAN_ID_SLOTS uint32 chanCounts"},
	{"FETCHED_AT_BLOCK", fetchedAtBlock, "seconds per idx timestamp block (8h): stored fetched_at is unix seconds ÷ this"},
	{"DELTA_FETCHED_MAX", deltaFetchedMax, "7-bit per-entry delta_fetched_at limit: writer clamp ceiling, reader bit mask"},
	{"LATEST_KEEP", latestKeep, "superseded L<seq> generations the backend GC keeps as a grace window for stale-db.gz readers"},
}

// tsTypes lists the Go structs whose JSON encodings the frontend reads,
// in emission order. Nested struct fields resolve through this same
// table, so a struct reachable from here must also be listed.
var tsTypes = []struct {
	name string
	doc  string
	typ  reflect.Type
}{
	{"IArticleWire", "one JSONL line in data/*.gz (backend ArticleData)", reflect.TypeOf(ArticleData{})},
	{"IFeedWire", "per-feed state inside a channel (backend Feed)", reflect.TypeOf(Feed{})},
	{"IChannelWire", "a db.gz channels{} value (backend Channel)", reflect.TypeOf(Channel{})},
	{"IDBWire", "db.gz itself (backend DBCore)", reflect.TypeOf(DBCore{})},
}

func (o *GenTSCmd) Run() error {
	out, err := generateTS()
	if err != nil {
		return err
	}
	if o.Check {
		disk, err := os.ReadFile(o.Out)
		if err != nil {
			return fmt.Errorf("read %s: %w (run `make generate`)", o.Out, err)
		}
		if !bytes.Equal(disk, out) {
			return fmt.Errorf("%s is stale relative to the Go declarations: run `make generate`", o.Out)
		}
		return nil
	}
	return os.WriteFile(o.Out, out, 0o644)
}

func generateTS() ([]byte, error) {
	var b strings.Builder
	b.WriteString(`// Code generated by srr gen-ts (backend/cmd_gents.go); DO NOT EDIT.
//
// The Go declarations in backend/ are the single source of truth for the
// writer↔reader data contract: the format constants in db.go and the JSON
// struct tags of ArticleData/Feed/Channel/DBCore. Regenerate with
// ` + "`make generate`; `make verify` fails when this file is stale." + `
//
// Wire-type conventions: ` + "`?`" + ` = json omitempty (key absent at the Go zero
// value); ` + "`| null`" + ` = a Go nil map/slice serialized while the key is present.
`)

	for _, c := range tsConsts {
		fmt.Fprintf(&b, "\n// %s\nexport const %s = %d\n", c.doc, c.name, c.value)
	}

	wireNames := map[reflect.Type]string{}
	for _, t := range tsTypes {
		wireNames[t.typ] = t.name
	}

	for _, t := range tsTypes {
		fmt.Fprintf(&b, "\n// Wire shape of %s.\nexport interface %s {\n", t.doc, t.name)
		for i := range t.typ.NumField() {
			f := t.typ.Field(i)
			if f.PkgPath != "" { // unexported: never serialized
				continue
			}
			if f.Anonymous {
				return nil, fmt.Errorf("%s.%s: embedded fields are not supported", t.typ.Name(), f.Name)
			}
			name, opts, _ := strings.Cut(f.Tag.Get("json"), ",")
			if name == "-" {
				continue
			}
			if name == "" {
				name = f.Name // encoding/json falls back to the Go field name
			}
			tsT, nilable, err := tsType(f.Type, wireNames)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", t.typ.Name(), f.Name, err)
			}
			switch {
			case strings.Contains(","+opts+",", ",omitempty,"):
				fmt.Fprintf(&b, "   %s?: %s // %s\n", name, tsT, f.Name)
			case nilable:
				fmt.Fprintf(&b, "   %s: %s | null // %s\n", name, tsT, f.Name)
			default:
				fmt.Fprintf(&b, "   %s: %s // %s\n", name, tsT, f.Name)
			}
		}
		b.WriteString("}\n")
	}
	return []byte(b.String()), nil
}

// tsType maps a Go type to its TypeScript wire type. nilable reports
// whether the Go zero value serializes as JSON null (map/slice/pointer).
func tsType(t reflect.Type, wireNames map[reflect.Type]string) (ts string, nilable bool, err error) {
	switch t.Kind() {
	case reflect.Pointer:
		ts, _, err = tsType(t.Elem(), wireNames)
		return ts, true, err
	case reflect.Slice:
		ts, _, err = tsType(t.Elem(), wireNames)
		return ts + "[]", true, err
	case reflect.Map:
		var key string
		switch t.Key().Kind() {
		case reflect.String:
			key = "string"
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			key = "number"
		default:
			return "", false, fmt.Errorf("unsupported map key type %s", t.Key())
		}
		ts, _, err = tsType(t.Elem(), wireNames)
		return fmt.Sprintf("Record<%s, %s>", key, ts), true, err
	case reflect.Struct:
		name, ok := wireNames[t]
		if !ok {
			return "", false, fmt.Errorf("struct %s not listed in tsTypes", t)
		}
		return name, false, nil
	case reflect.String:
		return "string", false, nil
	case reflect.Bool:
		return "boolean", false, nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", false, nil
	default:
		return "", false, fmt.Errorf("unsupported type %s", t)
	}
}
