// Code generated by srr gen-ts (backend/cmd_gents.go); DO NOT EDIT.
//
// The binary layouts in backend/idx_layout.go are the single source of truth
// for the byte-level half of the writer↔reader contract. This file is the Go
// side of that declaration — consumed by the writer (db_pack.go) and the Go
// reader (idx_read.go); frontend/src/js/format.gen.ts is the TS side, emitted
// from the same table in the same run. Regenerate with `make generate`;
// `make verify` fails when either file is stale.

package main

import (
	"encoding/binary"
	"fmt"
)

// Idx — one idx pack — variable-length header ‖ 2-byte entries ‖ boundary footer, little-endian throughout.

// idxHeaderEnd is the byte offset at which the header ends and the entry
// array begins.
func idxHeaderEnd(numSlots int) int {
	return 12 + numSlots*4
}

// idxEntriesEnd is the byte offset at which the entry array ends and the
// footer begins.
func idxEntriesEnd(numSlots int, packSize int) int {
	return idxHeaderEnd(numSlots) + packSize*2
}

// idxNumSlots reads the numSlots scalar out of a header prefix: how many cumulative per-feed counts follow — dense up to the high-water feed id when the pack was written.
func idxNumSlots(buf []byte) (int, error) {
	if len(buf) < 12 {
		return 0, fmt.Errorf("short header: %d < %d", len(buf), 12)
	}
	return int(binary.LittleEndian.Uint32(buf[8:])), nil
}

// idxHeaderSpan is the byte length of the variable-length header starting at
// buf[0] — how far a walk over concatenated headers advances to reach the
// next one. It errors when buf holds neither the prefix nor the counts the
// prefix declares.
func idxHeaderSpan(buf []byte) (int, error) {
	numSlots, err := idxNumSlots(buf)
	if err != nil {
		return 0, err
	}
	end := idxHeaderEnd(numSlots)
	if len(buf) < end {
		return 0, fmt.Errorf("short header: %d < %d (prefix plus the declared counts)", len(buf), end)
	}
	return end, nil
}

// idxValidate reports what is wrong with a buffer of size bytes claiming the
// given counts — nil when the shape is well-formed. Both readers state a
// corrupt pack in exactly these words.
func idxValidate(size int, numSlots int, packSize int) error {
	end := idxEntriesEnd(numSlots, packSize)
	if size < end {
		return fmt.Errorf("short body: have %d, want >= %d (header+%d entries)", size, end, packSize)
	}
	if (size-end)%2 != 0 {
		return fmt.Errorf("footer not whole u16 boundaries: %d trailing bytes", size-end)
	}
	return nil
}

// idxRaw is one decoded object, one member per declared field.
type idxRaw struct {
	PackIDBase  uint32   // the data packId the pack's first entry lives in
	PackOffBase uint32   // that entry's offset inside the data pack
	NumSlots    int      // how many cumulative per-feed counts follow — dense up to the high-water feed id when the pack was written
	FeedCounts  []uint32 // cumulative articles per feed BEFORE this pack, as of its first chron
	FeedIDs     []uint16 // one feed_id per article, in chron order
	Boundaries  []int    // ascending local entry indices at which the data packId advances by 1
}

// idxDecode decodes buf as one object holding packSize entries.
func idxDecode(buf []byte, packSize int) (idxRaw, error) {
	var raw idxRaw
	numSlots, err := idxNumSlots(buf)
	if err != nil {
		return raw, err
	}
	if err := idxValidate(len(buf), numSlots, packSize); err != nil {
		return raw, err
	}
	raw.PackIDBase = binary.LittleEndian.Uint32(buf[0:])
	raw.PackOffBase = binary.LittleEndian.Uint32(buf[4:])
	raw.NumSlots = int(binary.LittleEndian.Uint32(buf[8:]))
	raw.FeedCounts = make([]uint32, numSlots)
	for i := range raw.FeedCounts {
		raw.FeedCounts[i] = binary.LittleEndian.Uint32(buf[12+i*4:])
	}
	off := idxHeaderEnd(numSlots)
	raw.FeedIDs = make([]uint16, packSize)
	for i := range raw.FeedIDs {
		raw.FeedIDs[i] = binary.LittleEndian.Uint16(buf[off+i*2:])
	}
	raw.Boundaries = idxDecodeFooter(buf[idxEntriesEnd(numSlots, packSize):])
	return raw, nil
}

// idxDecodeFooter decodes a standalone footer — the bytes after the entry
// array, whose element count is implicit in their length.
func idxDecodeFooter(footer []byte) []int {
	out := make([]int, len(footer)/2)
	for i := range out {
		out[i] = int(binary.LittleEndian.Uint16(footer[i*2:]))
	}
	return out
}

// idxAppendHeader appends the variable-length header to dst. Every count is
// derived from the slice it counts, so a header can never claim a length its
// own bytes contradict.
func idxAppendHeader(dst []byte, packIDBase uint32, packOffBase uint32, feedCounts []uint32) []byte {
	dst = binary.LittleEndian.AppendUint32(dst, packIDBase)
	dst = binary.LittleEndian.AppendUint32(dst, packOffBase)
	dst = binary.LittleEndian.AppendUint32(dst, uint32(len(feedCounts)))
	for _, v := range feedCounts {
		dst = binary.LittleEndian.AppendUint32(dst, v)
	}
	return dst
}

// idxAppendEntry appends one entry to dst.
func idxAppendEntry(dst []byte, feedID uint16) []byte {
	return binary.LittleEndian.AppendUint16(dst, feedID)
}

// idxAppendFooter appends the whole footer to dst.
func idxAppendFooter(dst []byte, boundaries []int) []byte {
	for _, v := range boundaries {
		dst = binary.LittleEndian.AppendUint16(dst, uint16(v))
	}
	return dst
}
