import { afterAll, beforeAll, describe, expect, it } from "vitest"

import { IDX_PACK_SIZE } from "../../src/js/format.gen"
import { inspectValidate, srr, stressStore, type StressStore } from "../harness"
import { mountReader, type MountedReader } from "../contract/mount"

// Exhaustive stress + performance layer over a LARGE synthetic store (>50,000
// articles, >=150 feeds, multiple finalized idx packs/meta shards, generated by
// the production write path — see e2e/harness.ts stressStore()). It drives the
// REAL reader modules and measures three axes at scale:
//
//   navigation  — random-access loadArticle across every data pack, sequential
//                 stepping across the 50,000-entry idx-pack boundary, lazy idx
//                 pack fetching.
//   filtering   — full feed/tag walks via findRight/findLeft + countAll/countLeft,
//                 proving header-delta pack-skipping (a late-added feed's walk
//                 never touches the finalized idx pack it isn't in) and matching
//                 the Go writer's own count (srr inspect --filter).
//   query       — search.ts over the meta/ shards: bloom pruning (an absent term
//                 fetches zero finalized shards), short-query tail-only scan, and
//                 correctness of every hit against the data pack it addresses.
//
// Two metrics per scenario:
//   * request budget — reader.fetchMock records every pack fetch; the deterministic,
//     machine-independent regression guard. We assert these.
//   * wall time — performance.now() around each op; logged (PERF table) so a human
//     can watch it, with only loose sanity ceilings asserted (timing is flaky).

// --- pack-name classifiers (over the fetch shim's request pathnames) ----------
const RX = {
   idxFinal: /\/idx\/\d+\.gz$/, // finalized idx pack (idx/<n>.gz)
   idxSummary: /\/idx\/h\d+\.gz$/, // idx header summary (idx/h<N>.gz)
   idxLatest: /\/idx\/L\d+\.gz$/, // latest idx pack (idx/L<seq>.gz)
   data: /\/data\/(\d+|L\d+)\.gz$/, // any data pack
   metaShard: /\/meta\/\d+\.gz$/, // finalized meta shard (meta/<n>.gz)
   metaSummary: /\/meta\/s\d+\.gz$/, // meta bloom summary (meta/s<N>.gz)
   metaLatest: /\/meta\/L\d+\.gz$/, // latest meta tail (meta/L<seq>.gz)
}

function paths(reader: MountedReader, from = 0): string[] {
   return reader.fetchMock.mock.calls.slice(from).map((c) => new URL(String(c[0])).pathname)
}
function calls(reader: MountedReader): number {
   return reader.fetchMock.mock.calls.length
}
function count(ps: string[], rx: RegExp): number {
   return ps.filter((p) => rx.test(p)).length
}

// --- timing + a tiny deterministic PRNG --------------------------------------
interface PerfRow {
   axis: string
   op: string
   ms: number
   note: string
}
const PERF: PerfRow[] = []
function rec(axis: string, op: string, ms: number, note: string): void {
   PERF.push({ axis, op, ms: Math.round(ms * 10) / 10, note })
}
async function timed<T>(fn: () => Promise<T> | T): Promise<{ ms: number; val: T }> {
   const t0 = performance.now()
   const val = await fn()
   return { ms: performance.now() - t0, val }
}
// splitmix-ish LCG → reproducible "random" chron picks (no Math.random()).
function lcg(seed: number): () => number {
   let s = seed >>> 0
   return () => {
      s = (s * 1664525 + 1013904223) >>> 0
      return s / 0x100000000
   }
}

// Walk every match of `feeds` (a feed_id→add_idx map) left-to-right via the real
// reader primitive, exactly as nav does — the chronIdxs returned ARE the filter's
// reading order.
async function walkRight(reader: MountedReader, feeds: Map<number, number>): Promise<number[]> {
   const out: number[] = []
   for (let i = await reader.data.findRight(0, feeds); i !== -1; i = await reader.data.findRight(i + 1, feeds))
      out.push(i)
   return out
}

// Parse the Go writer's own filter count from `srr inspect --filter`.
function parseMatches(out: string): number {
   const m = out.match(/matches in idx\s*=\s*(\d+)/)
   if (!m) throw new Error("could not parse 'matches in idx' from inspect output:\n" + out)
   return Number(m[1])
}

interface FeedInfo {
   id: number
   total_art: number
   add_idx: number
   tag?: string
}
function feedInfos(reader: MountedReader): FeedInfo[] {
   return Object.values(reader.data.db.feeds) as unknown as FeedInfo[]
}

let STORE: StressStore
let feedsArr: FeedInfo[]

beforeAll(() => {
   STORE = stressStore()
   console.log(
      `\n[stress] store: ${STORE.dir}\n[stress] total_art=${STORE.total}${STORE.generated ? " (generated)" : " (reused)"}\n`,
   )
})

afterAll(() => {
   if (PERF.length === 0) return
   const pad = (s: string, n: number) => s.padEnd(n)
   const lines = [
      "",
      "════════════════════ STRESS PERF SUMMARY ════════════════════",
      `${pad("AXIS", 6)} ${pad("OPERATION", 34)} ${pad("ms", 9)} NOTE`,
      "──────────────────────────────────────────────────────────────",
      ...PERF.map((r) => `${pad(r.axis, 6)} ${pad(r.op, 34)} ${pad(String(r.ms), 9)} ${r.note}`),
      "══════════════════════════════════════════════════════════════",
      "",
   ]
   console.log(lines.join("\n"))
})

describe("stress: store scale invariants & O(1) boot", () => {
   let reader: MountedReader

   beforeAll(async () => {
      const r = await timed(() => mountReader(STORE.dir))
      reader = r.val
      feedsArr = feedInfos(reader)
      rec("boot", "data.init() (db.gz+summary+latest)", r.ms, `${calls(reader)} fetches`)
   })

   it("the store actually crosses the idx-pack boundary at scale", () => {
      expect(reader.data.db.total_art).toBeGreaterThan(IDX_PACK_SIZE)
      expect(reader.data.numFinalizedIdx()).toBeGreaterThanOrEqual(1)
      expect(reader.data.numFinalizedMeta()).toBeGreaterThanOrEqual(1)
      // >=150 feeds with articles, per the generator's own contract.
      expect(feedsArr.filter((f) => f.total_art > 0).length).toBeGreaterThanOrEqual(150)
   })

   it("boot is O(1): db.gz + idx summary + latest packs, NO finalized idx pack", () => {
      const ps = paths(reader)
      expect(ps.some((p) => p.endsWith("db.gz"))).toBe(true)
      expect(count(ps, RX.idxSummary)).toBe(1) // idx/h<N>.gz
      expect(count(ps, RX.idxLatest)).toBe(1) // idx/L<seq>.gz
      expect(count(ps, RX.idxFinal)).toBe(0) // the whole point: no idx/<n>.gz at boot
      // Lazy: search/meta untouched until first query.
      expect(count(ps, RX.metaShard) + count(ps, RX.metaSummary) + count(ps, RX.metaLatest)).toBe(0)
   })

   it("metaReady() is true → search & list-from-meta are available at scale", () => {
      expect(reader.data.metaReady()).toBe(true)
   })

   it("the Go writer's own full validation sweep passes", async () => {
      const r = await timed(() => inspectValidate(STORE.dir))
      expect(r.val).toContain("OK: all checks passed")
      rec("check", "srr inspect --validate", r.ms, "full bounds/meta/summary sweep")
   })
})

describe("stress: navigation", () => {
   let reader: MountedReader

   beforeAll(async () => {
      reader = await mountReader(STORE.dir)
   })

   it("random-access loadArticle across the whole store is correct & monotonic", async () => {
      const total = reader.data.db.total_art
      const S = Math.min(240, total)
      const rng = lcg(0x9e3779b9)
      const sample = Array.from({ length: S }, () => Math.floor(rng() * total)).sort((a, b) => a - b)

      const before = calls(reader)
      const { ms } = await timed(async () => {
         let prevP = -1
         for (const chron of sample) {
            const art = await reader.data.loadArticle(chron)
            expect(art, `chron ${chron}`).toBeDefined()
            expect(art.t, `chron ${chron} title`).toBeTruthy()
            // idx ↔ data agreement: the entry's feed_id resolves the same both ways.
            expect(art.f, `chron ${chron} feed`).toBe(await reader.data.getFeedId(chron))
            // chronIdx is published-ascending (generator stores in gidx order),
            // so a sorted sample's published times are strictly non-decreasing.
            const p = art.p ?? art.a
            expect(p, `chron ${chron} published >= prev`).toBeGreaterThanOrEqual(prevP)
            prevP = p
         }
      })

      const ps = paths(reader, before)
      // At most one finalized idx pack fetch per finalized pack the sample touched,
      // never more than the pack count — lazy, deduped.
      expect(count(ps, RX.idxFinal)).toBeLessThanOrEqual(reader.data.numFinalizedIdx())
      rec("nav", `random loadArticle ×${S}`, ms, `${count(ps, RX.data)} data + ${count(ps, RX.idxFinal)} idx fetches`)
   })

   it("sequential stepping ACROSS the 50,000-entry idx-pack boundary stays contiguous", async () => {
      const lo = IDX_PACK_SIZE - 6
      const hi = IDX_PACK_SIZE + 6
      const before = calls(reader)
      const { ms } = await timed(async () => {
         let prevP = -1
         for (let chron = lo; chron <= hi; chron++) {
            const art = await reader.data.loadArticle(chron)
            const p = art.p ?? art.a
            // strictly ascending across the boundary ⇒ bounds/offset resolution
            // is correct on BOTH idx packs (finalized 0 and latest).
            expect(p, `chron ${chron} strictly after ${chron - 1}`).toBeGreaterThan(prevP)
            prevP = p
         }
      })
      rec("nav", "step across idx boundary ×13", ms, `${count(paths(reader, before), RX.data)} data fetches`)
   })

   it("nav.right() drives the real state machine across the boundary", async () => {
      localStorage.clear()
      reader.nav.filter.clear() // [ALL]
      const start = IDX_PACK_SIZE - 3
      const first = await reader.nav.goTo(start)
      const visited = [first.article.p ?? first.article.a]
      const { ms } = await timed(async () => {
         for (let k = 0; k < 8; k++) {
            const sf = await reader.nav.right()
            visited.push(sf.article.p ?? sf.article.a)
         }
      })
      // 9 consecutive articles, strictly ascending published.
      for (let i = 1; i < visited.length; i++) expect(visited[i]).toBeGreaterThan(visited[i - 1])
      rec("nav", "nav.right() ×8 over boundary", ms, "state machine + prefetch")
   })
})

describe("stress: filtering", () => {
   let reader: MountedReader
   let busiest: FeedInfo
   let lateAdded: FeedInfo | undefined
   let topTag: string

   beforeAll(async () => {
      reader = await mountReader(STORE.dir)
      const arr = feedInfos(reader).filter((f) => f.total_art > 0)
      busiest = arr.reduce((a, b) => (b.total_art > a.total_art ? b : a))
      // a feed added in a post-finalize wave (its articles live only past the
      // first finalized idx pack), busiest such for the longest walk.
      lateAdded = arr
         .filter((f) => f.add_idx >= IDX_PACK_SIZE)
         .reduce<FeedInfo | undefined>((a, b) => (!a || b.total_art > a.total_art ? b : a), undefined)
      const byTag = new Map<string, number>()
      for (const f of arr) byTag.set(f.tag ?? "", (byTag.get(f.tag ?? "") ?? 0) + f.total_art)
      // the named tag (skip the "" untagged bucket) carrying the most articles
      topTag = [...byTag].filter(([t]) => t !== "").reduce((a, b) => (b[1] > a[1] ? b : a))[0]
   })

   it("busiest feed: countAll is sync (no fetch) and equals total_art", () => {
      const feeds = new Map([[busiest.id, busiest.add_idx]])
      const before = calls(reader)
      expect(reader.data.countAll(feeds)).toBe(busiest.total_art)
      expect(count(paths(reader, before), RX.data) + count(paths(reader, before), RX.idxFinal)).toBe(0)
   })

   it("busiest feed: full findRight walk matches total_art, ascending, all same feed", async () => {
      const feeds = new Map([[busiest.id, busiest.add_idx]])
      const before = calls(reader)
      const { ms, val: hits } = await timed(() => walkRight(reader, feeds))

      expect(hits.length).toBe(busiest.total_art)
      for (let i = 1; i < hits.length; i++) expect(hits[i]).toBeGreaterThan(hits[i - 1])
      // spot-check feed membership at both ends + middle (full check would be O(n) fetches)
      for (const c of [hits[0], hits[hits.length >> 1], hits[hits.length - 1]])
         expect(await reader.data.getFeedId(c)).toBe(busiest.id)
      expect(await reader.data.countLeft(reader.data.db.total_art, feeds)).toBe(busiest.total_art)

      const ps = paths(reader, before)
      // a feed present from the start spans every pack ⇒ the walk DOES touch the
      // finalized idx pack(s) — the contrast that proves skipping is real (below).
      expect(count(ps, RX.idxFinal)).toBeGreaterThanOrEqual(1)
      rec("filter", `walk busiest feed (${busiest.total_art})`, ms, `${count(ps, RX.idxFinal)} finalized idx fetched`)
   })

   it("busiest feed: the reader's count equals the Go writer's own (srr inspect --filter)", async () => {
      const out = await srr(STORE.dir, "inspect", "--filter", String(busiest.id))
      expect(parseMatches(out)).toBe(busiest.total_art)
   })

   it("late-added feed: full walk SKIPS the finalized idx pack via header deltas (zero finalized idx fetches)", async () => {
      if (!lateAdded) {
         // No post-finalize feed at this store size — skip rather than fail.
         rec("filter", "walk late-added feed", 0, "n/a (no add_idx>=IDX_PACK_SIZE feed)")
         return
      }
      // Fresh mount so finalized idx packs are genuinely unfetched at the start.
      const fresh = await mountReader(STORE.dir)
      const feeds = new Map([[lateAdded.id, lateAdded.add_idx]])
      const before = calls(fresh)
      const { ms, val: hits } = await timed(() => walkRight(fresh, feeds))

      expect(hits.length).toBe(lateAdded.total_art)
      // every match is past the boundary (feed only exists from add_idx on)
      expect(hits[0]).toBeGreaterThanOrEqual(lateAdded.add_idx)
      const ps = paths(fresh, before)
      // THE assertion: a feed absent from the finalized pack's frozen header is
      // skipped without ever fetching idx/<n>.gz.
      expect(count(ps, RX.idxFinal)).toBe(0)
      rec(
         "filter",
         `walk late-added feed (${lateAdded.total_art})`,
         ms,
         `${count(ps, RX.idxFinal)} finalized idx fetched (skipped)`,
      )
   })

   it("tag filter: walk equals the Go writer's count and stays in chronIdx order", async () => {
      reader.nav.filter.set([topTag])
      const feeds = reader.nav.filter.feeds
      const before = calls(reader)
      const { ms, val: hits } = await timed(() => walkRight(reader, feeds))
      for (let i = 1; i < hits.length; i++) expect(hits[i]).toBeGreaterThan(hits[i - 1])
      expect(reader.data.countAll(feeds)).toBe(hits.length)

      const out = await srr(STORE.dir, "inspect", "--filter", topTag)
      expect(parseMatches(out)).toBe(hits.length)
      rec(
         "filter",
         `walk tag "${topTag}" (${hits.length})`,
         ms,
         `${feeds.size} feeds, ${count(paths(reader, before), RX.idxFinal)} idx fetched`,
      )
   })
})

describe("stress: query (search over meta shards)", () => {
   let reader: MountedReader
   let search: typeof import("../../src/js/search")

   beforeAll(async () => {
      reader = await mountReader(STORE.dir)
      // same fresh module registry as the mounted data/nav ⇒ shares the fetch shim
      search = await import("../../src/js/search")
   })

   it("search is available and short queries scan tail-only (no shards, no summary)", async () => {
      expect(search.available()).toBe(true)
      expect(search.shortQuery("ab")).toBe(true)
      const before = calls(reader)
      const out: import("../../src/js/search").ISearchHit[] = []
      const { ms } = await timed(async () => {
         for await (const b of search.search("ab")) out.push(...b)
      })
      const ps = paths(reader, before)
      // a sub-trigram query can't prune ⇒ scans ONLY the latest tail.
      expect(count(ps, RX.metaShard)).toBe(0)
      expect(count(ps, RX.metaSummary)).toBe(0)
      rec("query", 'short "ab" (tail only)', ms, `${out.length} hits, 0 finalized shards`)
   })

   it("absent term: bloom prunes EVERY finalized shard (zero shard-body fetches)", async () => {
      const before = calls(reader)
      const out: import("../../src/js/search").ISearchHit[] = []
      const { ms } = await timed(async () => {
         for await (const b of search.search("qzxwjvbkpf")) out.push(...b)
      })
      expect(out).toEqual([])
      const ps = paths(reader, before)
      // summary + latest tail are consulted; NO finalized shard body is fetched.
      expect(count(ps, RX.metaShard)).toBe(0)
      rec("query", 'absent "qzxwjvbkpf" (pruned)', ms, `0 hits, ${count(ps, RX.metaShard)} shards fetched`)
   })

   it("common term: scans every finalized shard and every hit addresses its real article", async () => {
      const before = calls(reader)
      const out: import("../../src/js/search").ISearchHit[] = []
      const { ms } = await timed(async () => {
         for await (const b of search.search("dolor")) out.push(...b)
      })
      expect(out.length).toBeGreaterThan(0)

      // newest-first
      for (let i = 1; i < out.length; i++) expect(out[i].chron).toBeLessThan(out[i - 1].chron)
      // every returned title really contains the folded term
      for (const h of out) expect(search.fold(h.t)).toContain("dolor")
      // spot-check the meta projection vs the data pack it points at
      for (const h of out.slice(0, 12)) {
         const art = await reader.data.loadArticle(h.chron)
         expect(art.t, `chron ${h.chron}`).toBe(h.t)
         expect(art.f, `chron ${h.chron}`).toBe(h.f)
      }

      const ps = paths(reader, before)
      // a corpus word lives in every shard ⇒ no pruning ⇒ all finalized shards scanned.
      expect(count(ps, RX.metaShard)).toBe(reader.data.numFinalizedMeta())
      rec(
         "query",
         `common "dolor" (${out.length} hits)`,
         ms,
         `${count(ps, RX.metaShard)} / ${reader.data.numFinalizedMeta()} shards scanned`,
      )
   })

   it("multiple distinct queries complete within budget", async () => {
      const terms = ["ipsum", "tempor", "veniam", "laboris", "aliqua"]
      let totalHits = 0
      const { ms } = await timed(async () => {
         for (const t of terms) {
            for await (const b of search.search(t, 500)) totalHits += b.length
         }
      })
      expect(totalHits).toBeGreaterThan(0)
      // loose sanity ceiling — real is well under a second per term.
      expect(ms).toBeLessThan(60000)
      rec("query", `5 distinct terms (cap 500)`, ms, `${totalHits} total hits`)
   })
})
