// Code generated by srr gen-ts (backend/cmd_gents.go); DO NOT EDIT.
//
// The Go declarations in backend/ are the single source of truth for the
// writer↔reader data contract: the format constants in db.go, the pack-name
// grammar in store/main.go (PackSeries), and the JSON struct tags of
// ArticleData/MetaEntry/FeedPublic/Manifest/RootState. Regenerate with
// `make generate`; `make verify` fails when this file is stale.
//
// Wire-type conventions: `?` = json omitempty (key absent at the Go zero
// value); `| null` = a Go nil map/slice serialized while the key is present.

// store format version this build understands — the `v` of the root db.gz AND of every manifest it names; a store stamped higher was written by a newer srr and this reader cannot be trusted with it
export const DB_FORMAT_VERSION = 3

// entries per finalized idx pack (split threshold)
export const IDX_PACK_SIZE = 50000

// entries per finalized meta shard (the meta/ split stride; a divisor of IDX_PACK_SIZE)
export const META_PACK_SIZE = 5000

// cap on the newest-glance head projection in db.gz (db.head: the newest cards, chron order)
export const HEAD_MAX = 40

// bytes: the 2 leading uint32 LE idx-header state fields (packId/packOff bases)
export const IDX_STATE_SIZE = 8

// bytes: idx-header fixed prefix (2 state uint32s + numSlots uint32); the variable count array follows
export const IDX_HEADER_PREFIX = 12

// bytes per idx entry: feed_id uint16 LE (pack boundaries live in the footer)
export const IDX_ENTRY_SIZE = 2

// bytes per idx footer boundary: a uint16 LE local entry index where the data packId advances
export const IDX_BOUNDARY_SIZE = 2

// feed-id ceiling: feed_id is a uint16, ids run [0, this)
export const FEED_ID_CEILING = 65536

// default GC grace window K: generation manifests the backend keeps alongside the current one, and with them every object they name (docs/MANIFEST-SPEC.md §7)
export const KEEP_MANIFESTS = 32

// rune length of the sliding windows the search blooms index, per folded word
export const SEARCH_GRAM = 3

// bytes: fixed-size trigram bloom heading each finalized meta shard (and per shard in meta/s<N>.gz)
export const SEARCH_BLOOM_BYTES = 4096

// bloom bits set/tested per gram
export const SEARCH_BLOOM_K = 7

// The write-once pack-name grammar (backend store.PackSeries): one entry per
// pack-series directory. Every stem is an OPAQUE bare digit run — the kind
// letters ("L" latest generations, "h"/"s" summaries, "d" delta segments) were
// retired at the manifest cutover, because a name is now LISTED rather than
// derived and carries no meaning of its own. sw.ts builds its route regex from
// this table, mirroring the store's strict packKeyRe.
export const PACK_SERIES_KINDS: Record<string, string> = { idx: "", data: "", meta: "", manifest: "", seen: "" }

// Wire shape of one JSONL line in data/*.gz (backend ArticleData).
export interface IArticleWire {
   f: number // FeedID
   a: number // FetchedAt
   p?: number // Published
   t?: string // Title
   l?: string // Link
   c: string // Content
   g?: string // Lang
}

// Wire shape of one JSONL line in meta/*.gz (backend MetaEntry).
export interface IMetaWire {
   f: number // FeedID
   w: number // When
   t?: string // Title
}

// Wire shape of a manifest feeds{} value — the reader-facing half of a feed (backend FeedPublic).
export interface IFeedWire {
   title: string // Title
   url: string // URL
   wm?: number // Watermark
   ferr?: string // FetchError
   last_ok?: number // LastOK
   fail_streak?: number // FailStreak
   last_new?: number // LastNew
   tag?: string // Tag
   nt?: boolean // NoTitle
   exp?: number // ExpireDays
   xp?: number // Expired
   total_art: number // TotalArt
   add_idx: number // AddIdx
   cb?: number // ContentBytes
   ab?: number // AssetBytes
}

// Wire shape of one pack series' positional name list inside a manifest's `names` (backend seriesNamesWire): `b` base position, `r` run-length-encoded bare stems, `l` the tail's position.
export interface ISeriesNamesWire {
   b?: number // Base
   r?: [number, number][] // Runs
   l?: number // Tail
}

// Wire shape of a singleton object named by series + stem (backend StemRef).
export interface IStemRefWire {
   s: string // Series
   stem: number // Stem
}

// Wire shape of a derived summary object: series + stem + the finalized-pack count it covers (backend SummaryName).
export interface ISummaryNameWire {
   s: string // Series
   stem: number // Stem
   covers: number // Covers
}

// Wire shape of the live delta chain, oldest first (backend DeltaNames).
export interface IDeltaNamesWire {
   s: string // Series
   r: number[] | null // Stems
}

// Wire shape of manifest/<m>.gz — the immutable generation manifest (backend Manifest).
export interface IManifestWire {
   v: number // Version
   m: number // Num
   fetched_at: number // FetchedAt
   total_art: number // TotalArticles
   mt?: number // MetaTail
   na?: number // DeltaArticles
   head?: IMetaWire[] // Head
   hb?: number // HeadBase
   pack_off: number // PackOffset
   next_pid: number // NextPackID
   dby?: number // DeltaBytes
   gcm?: number // GCManifest
   inbox?: Record<string, number> // Inbox
   names: Record<string, unknown> | null // Names
   feeds: Record<number, IFeedWire> | null // Feeds
}

// Wire shape of db.gz itself — the mutable root pointer (backend RootState).
export interface IDBWire {
   v: number // Version
   m: number // ManifestNum
   t?: number // FetchedAt
}
