// Code generated by srr gen-ts (backend/cmd_gents.go); DO NOT EDIT.
//
// The Go declarations in backend/ are the single source of truth for the
// writer↔reader data contract: the format constants in db.go, the pack-name
// grammar in store/main.go (PackSeries), and the JSON struct tags of
// ArticleData/Feed/DBCore. Regenerate with
// `make generate`; `make verify` fails when this file is stale.
//
// Wire-type conventions: `?` = json omitempty (key absent at the Go zero
// value); `| null` = a Go nil map/slice serialized while the key is present.

// entries per finalized idx pack (split threshold)
export const IDX_PACK_SIZE = 50000

// entries per finalized meta shard (the meta/ split stride; a divisor of IDX_PACK_SIZE)
export const META_PACK_SIZE = 5000

// bytes: the 2 leading uint32 LE idx-header state fields (packId/packOff bases)
export const IDX_STATE_SIZE = 8

// bytes: idx-header fixed prefix (2 state uint32s + numSlots uint32); the variable count array follows
export const IDX_HEADER_PREFIX = 12

// bytes per idx entry: feed_id uint16 LE (pack boundaries live in the footer)
export const IDX_ENTRY_SIZE = 2

// bytes per idx footer boundary: a uint16 LE local entry index where the data packId advances
export const IDX_BOUNDARY_SIZE = 2

// feed-id ceiling: feed_id is a uint16, ids run [0, this)
export const FEED_ID_CEILING = 65536

// superseded L<seq> generations the backend GC keeps as a grace window for stale-db.gz readers
export const LATEST_KEEP = 2

// rune length of the sliding windows the search blooms index, per folded word
export const SEARCH_GRAM = 3

// bytes: fixed-size trigram bloom heading each finalized meta shard (and per shard in meta/s<N>.gz)
export const SEARCH_BLOOM_BYTES = 4096

// bloom bits set/tested per gram
export const SEARCH_BLOOM_K = 7

// The write-once pack-name grammar (backend store.PackSeries): per pack-series
// directory, the kind letters a stem may carry besides the finalized digit run
// — "L" latest generations, "h" idx header summaries, "s" search bloom
// summaries. sw.ts builds its route regex from this table and enforces
// kind-per-series in parsePackName, mirroring the store's strict packKeyRe.
export const PACK_SERIES_KINDS: Record<string, string> = { idx: "Lh", data: "L", meta: "Ls" }

// Wire shape of one JSONL line in data/*.gz (backend ArticleData).
export interface IArticleWire {
   f: number // FeedID
   a: number // FetchedAt
   p?: number // Published
   t?: string // Title
   l?: string // Link
   c: string // Content
}

// Wire shape of one JSONL line in meta/*.gz (backend MetaEntry).
export interface IMetaWire {
   f: number // FeedID
   w: number // When
   t?: string // Title
}

// Wire shape of a db.gz feeds{} value (backend Feed).
export interface IFeedWire {
   title: string // Title
   url: string // URL
   etag?: string // ETag
   last_modified?: string // LastModified
   wm?: number // Watermark
   bg?: number[] // BoundaryGUIDs
   ferr?: string // FetchError
   last_ok?: number // LastOK
   fail_streak?: number // FailStreak
   last_new?: number // LastNew
   tag?: string // Tag
   pipe?: string[] // Pipe
   ingest?: string // Ingest
   total_art: number // TotalArt
   add_idx: number // AddIdx
}

// Wire shape of db.gz itself (backend DBCore).
export interface IDBWire {
   seq?: number // Seq
   fetched_at: number // FetchedAt
   total_art: number // TotalArticles
   next_pid: number // NextPackID
   pack_off: number // PackOffset
   pipe?: string[] // Pipe
   ingest?: string // Ingest
   gen?: number // Gen
   hdrs?: number // HdrPacks
   mp?: number // MetaPacks
   mt?: number // MetaTail
   feeds: Record<number, IFeedWire> | null // Feeds
}
