name: Cron

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: /tmp/srr-cache
        key: srr-cache-${{ github.run_id }}
        restore-keys: srr-cache-
    - name: Fetch
      env:
        GH_TOKEN: ${{ github.token }}
        SRR_CONFIG_INLINE: ${{ secrets.SRR_CONFIG_INLINE }}
      run: |
        gh release download --repo ${{ github.repository }} --pattern srr-linux-amd64 --output srr
        chmod +x srr
        ./srr a fetch -d
