name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cron
    steps:
    - name: Fetch
      env:
        GH_TOKEN: ${{ github.token }}
        SRR_CONF: ${{ secrets.SRR_CONF }}
        SRR_CONFIG: srr.yaml
      run: |
        printf '%s' "$SRR_CONF" > "$SRR_CONFIG"
        gh release download --pattern srr-linux-amd64 --output srr
        chmod +x srr
        ./srr fetch -d
