name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - name: Fetch
      env:
        GH_TOKEN: ${{ github.token }}
        SRR_CONFIG_INLINE: ${{ secrets.SRR_CONFIG_INLINE }}
      run: |
        gh release download --repo ${{ github.repository }} --pattern srr-linux-amd64 --output srr
        chmod +x srr
        ./srr a fetch -d
