name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-toolchain
      with:
        node: "false"
    - run: make release
    - uses: softprops/action-gh-release@v3
      with:
        files: dist/srr-*

  pages:
    runs-on: ubuntu-latest
    environment: ci
    env:
      SRR_CONFIG_INLINE: ${{ secrets.SRR_CONFIG_INLINE }}
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-toolchain
      with:
        go: "false"
    - run: make build-fe
    - uses: actions/upload-pages-artifact@v5
      with:
        path: dist/srrf
    - uses: actions/deploy-pages@v5
